### ISSUE TITLE
DNU restore

### ISSUE THREAD

**Issue by loma** [stanlylau/tictactoe_csharp#1]
I try to run dnx restore but doesnt work, because i disabled the nuget.org source from my repo list.
I enabled it back and still doesnt work until i run dnu restore,  think it suppose to be dnu restore and dnx test :)

p.s try the first issue submit, lol

**Comment by stanlylau** [comment]
Good catch! I made the mistake myself and forgotten to fix the docs. If you're still online, you can send a pull request. =)

**Comment by stanlylau** [comment]
#2
